### ISSUE TITLE
Missing debug symbols for Android

### ISSUE THREAD

**Issue by AlienKevin** [irondash/cargokit#49]
# Issue Summary
Using the default config of cargokit with Flutter Rust Bridge V2, I observed that the panic backtrace works well on iOS. However, when I tested on Android, I noticed that the debug symbols are redacted as <Unknown>s.

# Issue Details
I tested the panic backtrace using [backtrace-rs](https://github.com/rust-lang/backtrace-rs) and [sentry-rust](https://github.com/getsentry/sentry-rust)'s panic monitoring mechanism. Flutter was ran under the debug mode with no modification to cargokit's configurations. I also tested on both a real Android 10 device and a Android 14 simulator. All experiments produced the same result: full trace on iOS but redacted trace on Android. I think this maybe due to missing debug symbols for Android.

Here are the panic backtraces for iOS and Android:
* iOS
```
PanicException(Jan 3 panic test!   0: backtrace::backtrace::trace_unsynchronized
   1: backtrace::backtrace::trace
   2: backtrace::capture::Backtrace::create
   3: backtrace::capture::Backtrace::new
   4: flutter_rust_bridge::misc::panic_backtrace::PanicBacktrace::setup::{{closure}}
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
   6: <sentry_panic::PanicIntegration as sentry_core::integration::Integration>::setup::{{closure}}::{{closure}}
   7: std::panicking::rust_panic_with_hook
   8: std::panicking::begin_panic_handler::{{closure}}
   9: std::sys_common::backtrace::__rust_end_short_backtrace
  10: _rust_begin_unwind
  11: core::panicking::panic_fmt
  12: rust_lib::api::api::combined_search
  13: rust_lib::frb_generated::wire_combined_search_impl::{{closure}}::{{closure}}::{{closure}}
  14: rust_lib::frb_generated::wire_combined_search_impl::{{closure}}::{{closure}}
  15: <flutter_rust_bridge::handler::implementation::executor::SimpleExecutor<EL,TP,AR> as flutter_rust_bridge::handler::executor::Executor>::execute_normal::{{closure}}::{{closure}}
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: std::panicking::try::do_call
  18: ___rust_try
  19: std::panicking::try
  20: std::panic::catch_unwind
  21: flutter_rust_bridge::misc::panic_backtrace::PanicBacktrace::catch_unwind
  22: <flutter_rust_bridge::handler::implementation::executor::SimpleExecutor<EL,TP,AR> as flutter_rust_bridge::handler::executor::Executor>::execute_normal::{{closure}}
  23: <F as threadpool::FnBox>::call_box
  24: threadpool::spawn_in_pool::{{closure}}
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
  27: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  28: std::panicking::try::do_call
  29: ___rust_try
  30: std::panicking::try
  31: std::thread::Builder::spawn_unchecked_::{{closure}}
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: std::sys::unix::thread::Thread::new::thread_start
  34: <unknown>
)
```

* Android
```
PanicException(Jan 3 panic test!   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: _ZL15__pthread_startPv
  31: __start_thread
)
```

# Proposed Changes
1. Default to bundle debug symbols in dev mode on Android
2. Offer ways to configure symbol stripping in dev vs release modes.

**Comment by knopp** [comment]
Cargokit doesn't strip the symbols. Symbols stripping can be configured in Cargo.toml, which is part of your project. 

For example: https://github.com/superlistapp/super_native_extensions/blob/main/super_native_extensions/rust/Cargo.toml

If not stripped by cargo, the symbols might also be stripped by gradle when packaging the app

https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/JniLibsPackagingOptions

**Comment by AlienKevin** [comment]
Thanks for the pointers. For future people's reference here are the two key steps you need to do:
1. If you wish to keep debug symbols in **release mode**, you have to turn on `debug` in your Rust code's cargo.toml:
```toml
[profile.release]
debug = true
```

2. To keep all debug symbols on Android, you need to add the following lines to your `android/app/build.gradle`:
```gradle
android {
    ..
    packagingOptions {
        jniLibs.keepDebugSymbols += "**/*.so"
    }
}
```
Note: This will keep debug symbols in both debug and release mode for **all your native dependencies**. You might want to specify only the `.so` file for your rust library to reduce the bundle size in production. Another thing to note is that you should add this `packagingOptions` in **your app's build.gradle**, not in the one in the `rust_builder` library generated by cargokit.
